from pydantic import BaseModel, Field
from typing import Any, Dict, Optional

class AnalysisDataInput(BaseModel):
    project_name: Optional[str] = Field(default="Unknown Project", description="Name of the project being analyzed")
    static_analysis: Any = Field(description="JSON data, string, or findings from the static analysis")
    dynamic_analysis: Any = Field(description="JSON data, string, or findings from the dynamic analysis")

class ReportResponse(BaseModel):
    report_markdown: str = Field(description="The comprehensive security report generated by the LLM in Markdown format")
